# Generated by Django 2.2.5 on 2019-09-03 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название планеты')),
            ],
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя Ситха')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.Planet')),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя рекрута')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.Planet')),
            ],
        ),
    ]
