# Generated by Django 2.2.5 on 2019-09-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0002_auto_20190906_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Номер вопроса'),
        ),
    ]
